In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [3]:
dataset = pd.read_csv('Data.csv')
x=dataset.iloc[: ,:-1].values
y=dataset.iloc[: ,-1].values

In [4]:
print(x)

[['SandaAdidas' 40.0 102000.0]
 ['SepatuConverse' 40.0 98000.0]
 ['SepatuFladeo' 40.0 100000.0]
 ['SepatuConverse' 39.0 95000.0]
 ['SepatuFladeo' 41.0 nan]
 ['SepatuAdidas' 40.0 95000.0]
 ['SepatuConverse' nan 100000.0]
 ['SepatuAdidas' 41.0 97000.0]
 ['SepatuFladeo' 41.0 105000.0]
 ['SepatuAdidas' 42.0 98000.0]]


In [5]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [7]:
print(x)

[['SandaAdidas' 40.0 102000.0]
 ['SepatuConverse' 40.0 98000.0]
 ['SepatuFladeo' 40.0 100000.0]
 ['SepatuConverse' 39.0 95000.0]
 ['SepatuFladeo' 41.0 98888.88888888889]
 ['SepatuAdidas' 40.0 95000.0]
 ['SepatuConverse' 40.44444444444444 100000.0]
 ['SepatuAdidas' 41.0 97000.0]
 ['SepatuFladeo' 41.0 105000.0]
 ['SepatuAdidas' 42.0 98000.0]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[1.0 0.0 0.0 0.0 40.0 102000.0]
 [0.0 0.0 1.0 0.0 40.0 98000.0]
 [0.0 0.0 0.0 1.0 40.0 100000.0]
 [0.0 0.0 1.0 0.0 39.0 95000.0]
 [0.0 0.0 0.0 1.0 41.0 98888.88888888889]
 [0.0 1.0 0.0 0.0 40.0 95000.0]
 [0.0 0.0 1.0 0.0 40.44444444444444 100000.0]
 [0.0 1.0 0.0 0.0 41.0 97000.0]
 [0.0 0.0 0.0 1.0 41.0 105000.0]
 [0.0 1.0 0.0 0.0 42.0 98000.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y=le.fit_transform(y)

In [11]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train , y_test = train_test_split(x,y, test_size=0.2 , random_state=1)

In [13]:
print(x_train)

[[0.0 0.0 1.0 0.0 40.44444444444444 100000.0]
 [0.0 0.0 0.0 1.0 41.0 98888.88888888889]
 [1.0 0.0 0.0 0.0 40.0 102000.0]
 [0.0 0.0 1.0 0.0 39.0 95000.0]
 [0.0 0.0 1.0 0.0 40.0 98000.0]
 [0.0 1.0 0.0 0.0 41.0 97000.0]
 [0.0 0.0 0.0 1.0 41.0 105000.0]
 [0.0 1.0 0.0 0.0 40.0 95000.0]]


In [14]:
print(x_test)

[[0.0 0.0 0.0 1.0 40.0 100000.0]
 [0.0 1.0 0.0 0.0 42.0 98000.0]]


In [15]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [16]:
print(y_test)

[0 1]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [18]:
print(x_train)

[[0.0 0.0 1.0 -0.5773502691896258 0.21147746721890198 0.3538824795847825]
 [0.0 0.0 0.0 1.7320508075688774 1.0573873360945316 0.008631279989873737]
 [1.0 0.0 0.0 -0.5773502691896258 -0.4652504278815973 0.9753346388556192]
 [0.0 0.0 1.0 -0.5773502691896258 -1.9878881918577262 -1.1997479185923092]
 [0.0 0.0 1.0 -0.5773502691896258 -0.4652504278815973 -0.2675696796860542]
 [0.0 1.0 0.0 -0.5773502691896258 1.0573873360945316 -0.5782957593214726]
 [0.0 0.0 0.0 1.7320508075688774 1.0573873360945316 1.9075128777618744]
 [0.0 1.0 0.0 -0.5773502691896258 -0.4652504278815973 -1.1997479185923092]]


In [19]:
print(x_test)

[[0.0 0.0 0.0 1.7320508075688774 -0.4652504278815973 0.3538824795847825]
 [0.0 1.0 0.0 -0.5773502691896258 2.58002510007066 -0.2675696796860542]]
